name: Checking code quality

on: [push]

jobs:
  # Job 1: Checkout and set up Python environment
  setup:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # Step 3: Upgrade pip to the latest version
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

  # Job 2: Lint code with flake8
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Step 1: Checkout code from repository (again, as each job runs in a new environment)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install flake8 for linting
      - name: Install flake8
        run: pip install flake8==7.1.1

      # Step 3: Lint the codebase with flake8
      - name: Lint with flake8
        run: flake8

  # Job 3: Type check code with mypy
  typecheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install mypy for type checking
      - name: Install mypy
        run: pip install mypy==1.11.2 "numpy>=1.22,<2.1"

      # Step 3: Type check the codebase with mypy
      - name: Type check with mypy
        run: mypy src
